## PANDAS

### Pandas is a Python library used to read, clean, organize, and analyze data. It is widely used in data analytics.

### Pandas support 2 data structure 
series
dataframe

In [2]:
import pandas as pd

## 1 Setup and Import

In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'3.0.5'

## 2 Creating Series and DataFrames

In [5]:
#pd.Series() ----> create a 1D labeled array

In [6]:
s = pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [7]:
s = pd.Series([10,20,30],index=['a','b','c'],name='values')
s

a    10
b    20
c    30
Name: values, dtype: int64

In [8]:
#pd.DataFrame() from a dict of lists ----> create a labeles 2D table

In [4]:
df = pd.DataFrame({
    'name' : ['Alice','Bob','Charlie','David'],
    'age' :[25,30,35,40],
    'city' : ['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [11]:
#pd.DataFrame() from a list of dicts

In [12]:
pd.DataFrame([{'a':1,'b':2},{'a':3,'b':4}])

   a  b
0  1  2
1  3  4

In [13]:
#pd.DataFrame() from a Numpy array

In [14]:
pd.DataFrame(np.arange(6).reshape(2,3),columns =['x','y','z'])

   x  y  z
0  0  1  2
1  3  4  5

## 3 Attributes and Inspection

In [16]:
df.shape #.shape ---->(rows,columns)

(4, 3)

In [17]:
df.columns #.columns ---->columns label

Index(['name', 'age', 'city'], dtype='str')

In [18]:
df.index  #.index ---->row label

RangeIndex(start=0, stop=4, step=1)

In [19]:
df.dtypes  #.dtypes ----> data types of each column

name      str
age     int64
city      str
dtype: object

In [20]:
df.values  #.values ----> underlying numpy array

array([['Alice', 25, 'NY'],
       ['Bob', 30, 'LA'],
       ['Charlie', 35, 'SF'],
       ['David', 40, 'NY']], dtype=object)

In [21]:
df.size  #.size ----> total number of elements

12

In [23]:
df.head()  #.head----> first n rows

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [25]:
df.tail(2)  #.tail----> last n rows

      name  age city
2  Charlie   35   SF
3    David   40   NY

In [26]:
df.info()  #.info---->

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [27]:
df.describe()  #.describe---->

             age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [28]:
df.memory_usage()  #.memory_usage----> memory used by each column

Index    132
name      32
age       32
city      32
dtype: int64

## 4 Selection and Indexing(loc,iloc,at,iat)

In [38]:
df.set_index('name',inplace=False) # set a column as a row index

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

In [37]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [5]:
df['age'] #single column returns a series

0    25
1    30
2    35
3    40
Name: age, dtype: int64

In [6]:
df[['name','age']] # a list of column returns a DataFrame

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [7]:
df.loc[0] # Select a row by label

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [9]:
df.loc[0,'age'] #Select a scalar value by label

np.int64(25)

In [11]:
df.loc[0:2,['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [16]:
df.iloc[0] #select a scalar value by integer position

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [17]:
df.iloc[0,1]

np.int64(25)

In [19]:
df.iloc[0:2,0:2] #select a row and column by integer position

    name  age
0  Alice   25
1    Bob   30

In [21]:
df.at[0,'age']

np.int64(25)

In [22]:
df.iat[0,1]

np.int64(25)

## 5 Filtering and Boolean Indexing

In [23]:
df[df['age']>28] #simple condition ---->

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [30]:
df[(df['age']>25) & (df['city']== 'NY')] #multiple condition ---->combine with & (and)/ |or)

    name  age city
3  David   40   NY

In [31]:
df[(df['age']>36) | (df['city']=='NY')]

    name  age city
0  Alice   25   NY
3  David   40   NY

In [34]:
df[(df['name']=='Bob')| (df['city']=='NY')]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [37]:
df[df['city'].isin(['NY','LA'])] #filter rows where a column matches a set of values

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [40]:
df.query('age >28 and city =="NY"') #filter using a readable string expression

    name  age city
3  David   40   NY

In [41]:
df.where(df['age'] >28) #keep matching values ,replace other with NAN

      name   age city
0      NaN   NaN  NaN
1      Bob  30.0   LA
2  Charlie  35.0   SF
3    David  40.0   NY

In [42]:
df.mask(df['age'] >28) #opposite of where() ,replace matching values with NAN

    name   age city
0  Alice  25.0   NY
1    NaN   NaN  NaN
2    NaN   NaN  NaN
3    NaN   NaN  NaN

## 6 Adding ,Modifying and Dropping Columns/Rows

In [43]:
df2 =df.copy()

In [44]:
df2

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [52]:
df2['senior'] = df2['age']>30 #adding a new column for exiting one

In [53]:
df2

      name  age city  senior  age_plus_5
0    Alice   25   NY   False          30
1      Bob   30   LA   False          35
2  Charlie   35   SF    True          40
3    David   40   NY    True          45

In [54]:
df2['age_plus_5']= df2['age']+5 #adding a computed column
df2

      name  age city  senior  age_plus_5
0    Alice   25   NY   False          30
1      Bob   30   LA   False          35
2  Charlie   35   SF    True          40
3    David   40   NY    True          45

In [57]:
df2.rename(columns={'city':'location'}, inplace=True)
df2

      name  age location  senior  age_plus_5
0    Alice   25       NY   False          30
1      Bob   30       LA   False          35
2  Charlie   35       SF    True          40
3    David   40       NY    True          45

In [58]:
df2.drop(columns={'age_plus_5'}, inplace=True)
df2

      name  age location  senior
0    Alice   25       NY   False
1      Bob   30       LA   False
2  Charlie   35       SF    True
3    David   40       NY    True

In [60]:
df2.drop(index=0,inplace=False) #drop a row

      name  age location  senior
1      Bob   30       LA   False
2  Charlie   35       SF    True
3    David   40       NY    True

In [61]:
df2.insert(1,'id',range(len(df2)))
df2

      name  id  age location  senior
0    Alice   0   25       NY   False
1      Bob   1   30       LA   False
2  Charlie   2   35       SF    True
3    David   3   40       NY    True

In [63]:
df2.assign(double_age=df2['age'] *2)

      name  id  age location  senior  double_age
0    Alice   0   25       NY   False          50
1      Bob   1   30       LA   False          60
2  Charlie   2   35       SF    True          70
3    David   3   40       NY    True          80

## 7 Handling Missing Data

In [6]:
df_na =pd.DataFrame({'a':[1,np.nan,3],'b':[np.nan,2,3]})
df_na

     a    b
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0

In [7]:
#  .isna() ---> Boolean mask of missing values
df_na.isna()

       a      b
0  False   True
1   True  False
2  False  False

In [8]:
# .notna() ----> opposite of .isna()
df_na.notna()

       a      b
0   True  False
1  False   True
2   True   True

In [9]:
#df_na.isnull().sum() ---> Count of missing values per columns
df_na.isnull().sum()

a    1
b    1
dtype: int64

In [10]:
# .dropna()-----> Drop rows containing any NaN
df_na.dropna()

     a    b
2  3.0  3.0

In [11]:
# .dropna(axis=1)-----> Drop columns containing any NaN
df_na.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [12]:
#  .fillna() ---->  fill missing values with constant
df_na.fillna(0)

     a    b
0  1.0  0.0
1  0.0  2.0
2  3.0  3.0

In [13]:
#   .ffill() -----> Forward fill missing values
df_na.ffill()

     a    b
0  1.0  NaN
1  1.0  2.0
2  3.0  3.0

In [14]:
#   .bfill() -----> Backward fill missing values
df_na.bfill()

     a    b
0  1.0  2.0
1  3.0  2.0
2  3.0  3.0

# 8 Sorting And Ranking

In [15]:
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [16]:
# .sort_values() ----> Arrange the values in ascending order
df.sort_values('age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [17]:
df.sort_values(['city','age'],ascending=[True,False])

      name  age city
1      Bob   30   LA
3    David   40   NY
0    Alice   25   NY
2  Charlie   35   SF

In [18]:
# .sort_index() ----> Sort rows by the index
df.sort_index()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [19]:
# .rank() ----> Rank values within a column
df['age'].rank

<bound method NDFrame.rank of 0    25
1    30
2    35
3    40
Name: age, dtype: int64>

In [20]:
# .nlargest() ----> Top n rows by a column
df.nlargest(2,'age')

      name  age city
3    David   40   NY
2  Charlie   35   SF

In [21]:
# .nsmallest()----> Bottom n rows by a column
df.nsmallest(3,'age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

# 9 Aggregation and Statistics

In [22]:
# .sum() / .mean() / .median() ------> Basic Aggregations
df['age'].sum(), df['age'].mean(), df['age'].median()

(np.int64(130), np.float64(32.5), np.float64(32.5))

In [23]:
# .std() / .var() ----> Spread of data
df['age'].std(), df['age'].var()

(np.float64(6.454972243679028), np.float64(41.666666666666664))

In [24]:
# .min() / .max() ----> Smallest and Largest value
df['age'].min(), df['age'].max()

(np.int64(25), np.int64(40))

In [25]:
# .count() ---> Number of not null values
df['age'].count()

np.int64(4)

In [26]:
# .agg()----> Apply a multiple aggregation functions at once
df.agg({'age':['mean','max','min']})

       age
mean  32.5
max   40.0
min   25.0

In [27]:
# .corr() ----->correlation matrix of numeric columns
df.corr(numeric_only=True)

     age
age  1.0

In [28]:
# .mode() ---->Most frequently occuring value
df['city'].mode()

0    NY
Name: city, dtype: str

## 10 GroupBy Operation

In [6]:
g=df.groupby('city')

In [ ]:
#.size() ----->number of rows in each group

In [8]:
g.size()

city
LA    1
NY    2
SF    1
dtype: int64

In [9]:
#Group then aggregate a single column

In [10]:
g['age'].mean()

city
LA    30.0
NY    32.5
SF    35.0
Name: age, dtype: float64

In [11]:
#.agg() on a groupby-----> multiple aggregation per group

In [12]:
g.agg({'age':['mean','sum']})

       age
      mean sum
city
LA    30.0  30
NY    32.5  65
SF    35.0  35

In [13]:
#.apply() on a groupby-----> custom function per group

In [16]:
g.apply(lambda x:x ['age'].max()-x['age'].min())

city
LA     0
NY    15
SF     0
dtype: int64

In [19]:
add = lambda a,b : a+b

In [20]:
add(4,5)

9

In [21]:
#iterating over group with a for loop

In [22]:
for name, group in g:
    print(name)
    print(group)

LA
  name  age city
1  Bob   30   LA
NY
    name  age city
0  Alice   25   NY
3  David   40   NY
SF
      name  age city
2  Charlie   35   SF

In [23]:
#get_group --> retrive a specific group

In [24]:
g.get_group('NY')

    name  age city
0  Alice   25   NY
3  David   40   NY

In [25]:
#data

In [28]:
df.to_csv('data.csv',index=False)
pd.read_csv('data.csv')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [29]:
df.to_json('data.json',orient='records')
pd.read_json('data.json')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [32]:
df.to_excel('data.xlsx',index=False)
pd.read_excel('data.xlsx')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [31]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [33]:
df.to_dict(orient='records')

[{'name': 'Alice', 'age': 25, 'city': 'NY'},
 {'name': 'Bob', 'age': 30, 'city': 'LA'},
 {'name': 'Charlie', 'age': 35, 'city': 'SF'},
 {'name': 'David', 'age': 40, 'city': 'NY'}]

In [34]:
pd.DataFrame.from_dict({'a':[1,2]})

   a
0  1
1  2